env:
  es2021: true
  node: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  consistent-return: 0
  linebreak-style: 0
  arrow-body-style: 0
  no-console: 0
  no-return-await: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions:
    - error
    - js: always